### ISSUE TITLE
Properly distinguish between unit tests and integration tests

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/webmangler#113]
# Engineering Initiative

## Description

Currently, the test suites are a bit of a mix of unit tests and integration tests. As the project grows this is becoming a bit confusing when reviewing, adding, or updating tests. It is also starting to affect the usability of the tests, as the "integration" test cases are starting to take quite some time to run. Splitting the integration tests and unit tests should dramatically decrease the time it takes to run unit tests, making them usable for verifying changes quickly and git hook. The integration tests can be run if needed and, of course, in the CI pipelines.

Converting all the existing tests will, clearly, take quite some effort to update. I will  keep this issue updated with progress towards this initiative.

## Approach

Following #158, all `__tests__` folders should be split up into the following folders:

- `__tests__/performance`: For [performance tests](https://en.wikipedia.org/wiki/Benchmark_(computing)).
- `__tests__/integration`: For [integration tests](https://en.wikipedia.org/wiki/Integration_testing).
- `__tests__/unit`: For [unit tests](https://en.wikipedia.org/wiki/Unit_testing).
- `__tests__/common`: For re-usable helper functions and mocks. This directory should also contain a `*.test.ts` file for every non-`index.ts` file. These should be unit tests and are are run together with unit tests.

with appropriate `.test.ts` file in each of them.

For now, all tests (unit and integration) are always run when using the `npm run test` command. In the future - when there's good coverage - a `npm run test:unit` and `npm run test:integration` command may be added to support running only the unit tests and only the integration tests respectively.

## ~~Progress - unit & integration tests~~

- [x] `packages/benchmarking` (#212)
- [x] `packages/cli` (#235)
- [x] `packages/core` (#263)
- [x] `packages/language-css` (#158)
- [x] `packages/language-html` (#252)
- [x] `packages/language-js` (#227)
- [x] `packages/language-utils` (#218)
- [x] `packages/mangler-css-classes` (#169)
- [x] `packages/mangler-css-variables` (#193)
- [x] `packages/mangler-html-attributes` (#176)
- [x] `packages/mangler-html-ids` (#216)
- [x] `packages/mangler-utils` (#196)
- [x] `packages/testing` (#190)
- [x] `packages/types` (_no tests_)

## ~~Progress - performance tests~~

- [x] `packages/benchmarking` (_no performance tests_)
- [x] `packages/cli` (_no performance tests_)
- [x] `packages/core` (#261)
- [x] `packages/language-css` (#217)
- [x] `packages/language-html` (#252)
- [x] `packages/language-js` (#227)
- [x] `packages/language-utils` (_no performance tests_)
- [x] `packages/mangler-css-classes` (_no performance tests_)
- [x] `packages/mangler-css-variables` (_no performance tests_)
- [x] `packages/mangler-html-attributes` (_no performance tests_)
- [x] `packages/mangler-html-ids` (_no performance tests_)
- [x] `packages/mangler-utils` (_no performance tests_)
- [x] `packages/testing` (_no performance tests_)
- [x] `packages/types` (_no performance tests_)

## Followup

- [x] Run only unit tests in [the pre-push hook](https://github.com/ericcornelissen/webmangler/blob/main/scripts/hooks/pre-push) (#278)
- [x] Separate unit and integration test coverage (#417)
- [x] Separate unit and integration tests in the CI (#417)
- [x] Update [test suffixes](https://github.com/ericcornelissen/webmangler/blob/fdd521f61867ffe5b57cf331e279d99de12a6423/.values.cjs#L3-L4) (#261)
- [x] Don't [run test files directly in `__tests__`](https://github.com/ericcornelissen/webmangler/blob/76f4e6afebf466d85b19ed306e4d494dd2bd0749/.values.cjs#L26) (#278)
- [x] Update [the CI filters for performance tests](https://github.com/ericcornelissen/webmangler/blob/fdd521f61867ffe5b57cf331e279d99de12a6423/scripts/ci/get-filters.js#L42-L53) (#261)
- [x] Update [the CI filters for tests](https://github.com/ericcornelissen/webmangler/blob/fdd521f61867ffe5b57cf331e279d99de12a6423/scripts/ci/get-filters.js#L54-L67) (#278)

## Related Issues & Pull Requests

- #108
- #117
- #121 
- #134
- #158
- #162
- #164
- #169
- #174
- #176
- #190
- #193
- #196
- #197
- #202
- #212
- #216
- #217
- #218
- #227
- #235
- #252
- #261
- #263
- #278
- #385
- #391
- #415
- #417

**Comment by ericcornelissen** [comment]
Between the two proposals for properly separating unit and integration tests at the file level (#158 and #164) I have chosen to move forward with the option where tests of a different type are put in a separate repository: #158.

The primary reason for this is that the other proposal (#164) can lead to situations where there are "too many" test files in one directory. While "too many" is clearly subjective, having 3 times (or more, if fuzz and/or property tests are added) as many tests files as source files in one directory can be overwhelming. The subfolder approach reduces this to folder that have at most as many tests as there are source files.

Additionally, it could be argued that _unconventional_ extensions (especially `.intg.ts`) are bad for new contributors. I personally don't see this as too much of a problem, but can definitely see why going with more _standard_ extensions helps newcomers to the project find their way around.

**Comment by ericcornelissen** [comment]
When #202 is merged, the issue description should be updated to reflect the change from "benchmarking" to "performance testing".
