### ISSUE TITLE
Use mutation testing to improve (unit) tests

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/webmangler#124]
# Engineering Initiative

## Description

With #121 merged the packages can now be mutation tested. This issue is to keep track of which packages have been updated based on the result of running mutation tests.

The goal of mutation testing is to improve (unit) tests to actually verify the implementation, rather than just provide coverage. Mutation testing achieves this by mutating the source code and running the tests to see if the change is detected. If the change was not detected it is saved as a "mutant" and reported back to the user. If no mutants are found, that implies changes to the code base will be caught by the tests.

## Progress

- [x] `packages/benchmarking` (#212)
- [x] `packages/cli` (#249)
- [x] `packages/core` (#317)
- [x] `packages/language-css` (#197)
- [x] `packages/language-html` (#269)
- [x] `packages/language-js` (#227)
- [x] `packages/language-utils` (#218)
- [x] `packages/mangler-css-classes` (#260)
- [x] `packages/mangler-css-variables` (#193)
- [x] `packages/mangler-html-attributes` (#267)
- [x] `packages/mangler-html-ids` (#216)
- [x] `packages/mangler-utils` (#196)
- [x] `packages/testing` (#253)
- [x] `packages/types` (no tests)

## Followup

- [x] Make the [`get-filters.js` filter for mutation testing](https://github.com/ericcornelissen/webmangler/blob/85dbc2aab2c6e19d17455644f57a30551f72d4fa/scripts/ci/get-filters.js#L59-L60) dynamic (#324)

## Related Issues & Pull Requests
 
- #113
- #117
- #121 
- #134
- #140
- #142
- #153
- #193
- #196
- #197
- #204
- #212
- #216
- #218
- #227
- #249
- #253
- #260
- #267
- #269
- #288
- #317

**Comment by ericcornelissen** [comment]
If #204 is merged, [which restricts mutation tests to unit tests](https://github.com/ericcornelissen/webmangler/commit/c7be864b6e59491d527ca100e54ff807e351e6f2), the list should be updated as various checked packages are not quite done yet. In particular:

- `packages/benchmarking`: Doesn't have dedicated unit tests yet (see also #113)
- `language/html`: Doesn't have dedicated unit tests yet (see also #113)
- `language/js`: Doesn't meet the 50% threshold using only unit tests

**Comment by ericcornelissen** [comment]
Consider replacing [mutation report artifects](https://github.com/ericcornelissen/webmangler/blob/e2dee15a288962cd9fee338b1e6baac4c110fc53/.github/workflows/code-checks.yml#L222-L227) by using [Stryker Dashboard](https://dashboard.stryker-mutator.io/) ([documentation](https://stryker-mutator.io/docs/General/dashboard)). Note the following line from the documentation:

> `MODULE`: Optional. If you want to store multiple reports for a version, you can use this value to separate them logically, for example, in a mono-repo setup where each package (or project or module) delivers a report.
