### ISSUE TITLE
Use "lib" for published JavaScript code

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/webmangler#150]
# Chore

## Description

Currently, most of [the package](https://github.com/ericcornelissen/webmangler/tree/f54d73841842bc48865d728f9a8eb378c59cd170/packages) compile into [an `"outDir"` named "build"](https://github.com/ericcornelissen/webmangler/blob/f54d73841842bc48865d728f9a8eb378c59cd170/packages/core/tsconfig.json#L5). This is fine in theory - as it is entirely abstracted from the package user - but a clearer and more standard name would still be preferable.

## Notes

For some package, just changing the `tsconfig.json` file is enough but for some more changes are required. For example [to keep the internal dependencies working](https://github.com/ericcornelissen/webmangler/blob/f54d73841842bc48865d728f9a8eb378c59cd170/tsconfig.json#L16) or [to keep the package exports working](https://github.com/ericcornelissen/webmangler/blob/f54d73841842bc48865d728f9a8eb378c59cd170/packages/core/package.json#L8).

## Progress

- [ ] benchmarking
- [ ] cli
- [ ] core
- [ ] language-css
- [ ] language-html
- [ ] language-js
- [ ] language-utils
- [ ] mangler-css-classes
- [ ] mangler-css-variables
- [ ] mangler-html-attributes
- [ ] mangler-html-ids
- [ ] mangler-utils
- [ ] testing
- [ ] types

---

_As this issue concerns all package, the labels of individual packages won't be added._

**Comment by ericcornelissen** [comment]
[The nyc configuration file](https://github.com/ericcornelissen/webmangler/blob/main/nyc.config.cjs) needs to be updated to exclude the `lib/` directory when creating a coverage report.

**Comment by ericcornelissen** [comment]
If #194 (specifically 70d0ff02c917c8d4f79866fb8c61edff6f67e3fa) gets merged, then once all packages have been changed from _build_ to _lib_ the cached paths should be updated to omit `packages/*/build`.
