### ISSUE TITLE
Improve project security

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/webmangler#178]
# Task

## Description

Improve the overall security of the project by employing security best practices. Below you can find an overview of things that can be improved as of a3aed3c36e251e47128759c4c42adb560c4f41a9. Other suggestions are welcome.

## Tasks

- [x] Use an LTS Node.js version for development. (#177)
- [ ] Pin newly added npm dependencies by default.
- [ ] Pin actions used in GitHub Actions workflows.
- [ ] Reduce [permissions in GitHub Actions workflows](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions) (principle of least privilege).
