### ISSUE TITLE
Remove per-package `package-lock.json`

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/webmangler#205]
# Chore

## Description

Since the adoption of _npm workspaces_ (#186), the per-package `package-lock.json` files are no longer necessary. This ticket is intended to track the progress of removing these files from the project.

### Notes

1. The intent is to remove the `package-lock.json` of each package gradually over time whenever a commit would've changed the file in the old setup.
2. The `package-lock.json` file should be ignored through `.gitignore` to prevent it from showing up in the git history in case anyone runs `npm install` from the package directory.

## Progress

- [ ] benchmarking
- [ ] cli
- [ ] core
- [ ] language-css
- [ ] language-html
- [ ] language-js
- [ ] language-utils
- [ ] mangler-css-classes
- [ ] mangler-css-variables
- [ ] mangler-html-attributes
- [ ] mangler-html-ids
- [ ] mangler-utils
- [ ] testing
- [ ] types

---

_As this issue concerns all package, the labels of individual packages won't be added._
