### ISSUE TITLE
Republish the core and CLI in the webmangler namespace

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/webmangler#353]
# Initiative

## Packages

- [webmangler (core)](https://github.com/ericcornelissen/webmangler/tree/40121283da7ab8b1c0d82a75baacc4b614d465f6/packages/core)
- [webmangler-cli](https://github.com/ericcornelissen/webmangler/tree/40121283da7ab8b1c0d82a75baacc4b614d465f6/packages/cli)

## Description

Most packages are published with a name like `@webmanger/package` except for the core (named `webmangler`) and CLI (named `webmangler-cli`). This should be consolidated so that:

- `webmangler` published as `@webmangler/core`
- `webmangler-cli` published as `@webmangler/cli`

The main motivators are:

- Properly using the `@webmangler` namespace
- Cleaner `package.json`s for consumers:
  
  ```diff
    "dependencies": {
      "@webmangler/a-package": "3.1.4",
  +   "@webmangler/cli": "0.5.7",
  +   "@webmangler/core": "2.7.1",
      "@webmangler/some-package": "1.4.1",
      "some-other-package": "1.6.8",
  -   "webmangler": "2.7.1",
  -   "webmangler-cli": "0.5.7",
    }
  ```

## Progress

- [x] [webmangler](https://github.com/ericcornelissen/webmangler/tree/40121283da7ab8b1c0d82a75baacc4b614d465f6/packages/core) (#424)
- [x] [webmangler-cli](https://github.com/ericcornelissen/webmangler/tree/40121283da7ab8b1c0d82a75baacc4b614d465f6/packages/cli) (#424)
- [x] Update the issue templates (#424)
- [x] Add deprecation warning to [`npmjs.com/package/webmangler`](https://www.npmjs.com/package/webmangler)
- [x] Add deprecation warning to [`npmjs.com/package/webmangler-cli`](https://www.npmjs.com/package/webmangler-cli)
