### ISSUE TITLE
Backfill references in CHANGELOGs

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/webmangler#369]
# Chore

## Description

Recent entries to CHANGELOGs include a link reference to a Pull Request or commit that implemented that particular change. This practice wasn't there historically, so some CHANGELOGs do not include a reference for all changes. For consistency, we want to have a reference for all changes in every CHANGELOG.

### Notes

1. A reference must be either a to a Pull Request (e.g. `([#314])`, or see [this `CHANGELOG.md`](https://github.com/ericcornelissen/webmangler/blob/6c370da3df6bdf5307c56971cec2f815c6284967/packages/cli/CHANGELOG.md)) or to a commit (e.g. `([6175995])`, or see [this `CHANGELOG.md`](https://github.com/ericcornelissen/webmangler/blob/6c370da3df6bdf5307c56971cec2f815c6284967/packages/testing/CHANGELOG.md)).
1. If you want to contribute to this issue, please leave a comment with the name of the package of which you plan to backfill the CHANGELOG.
1. The backfilling of the CHANGELOG does not receive an entry in the CHANGELOG.
1. Occasionally we will incorporate the backfilling of a CHANGELOG with the release of the respective package. There will be an indication when this is happening in the issue description.

## Progress

- [ ] benchmarking
- [ ] cli
- [ ] core
- [x] language-css
- [x] language-html
- [x] language-js
- [x] language-utils
- [ ] mangler-css-classes (#368)
- [ ] mangler-css-variables (#368)
- [ ] mangler-html-attributes (#368)
- [ ] mangler-html-ids
- [x] mangler-utils 
- [x] testing
- [x] types

---

_As this issue concerns all package, the labels of individual packages won't be added._
