### ISSUE TITLE
Use allowlist-based `.npmignore` files

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/webmangler#421]
# Initiative

## Description

The `.npmignore` of all packages in this project currently use a "blocklist" approach - i.e. they specify globs of things that shouldn't be published. This should be updated to use an "allowlist" instead - i.e. they should specify globs of things that should be published.

### Example

```diff
- src/
- tsconfig.*
- 
- # JavaScript files that are always empty
- types.js
+ *
+ 
+ # Allowlist
+ !build/**
+ build/**/types.js
+ !CHANGELOG.m
+ !LICENSE
+ !package.json
+ !README.md
```

## Progress

- [ ] benchmarking
- [ ] cli
- [ ] core
- [ ] language-css
- [ ] language-html
- [ ] language-js
- [ ] language-utils
- [ ] mangler-css-classes
- [ ] mangler-css-variables
- [ ] mangler-html-attributes
- [ ] mangler-html-ids
- [ ] mangler-utils
- [ ] testing
- [ ] types

## Related

- #150
- #205

---

_As this issue concerns all package, the labels of individual packages won't be added._
